branches:
  only:
  - master
language: c
script: 
  - echo $HOLA
  - python hello.py
notifications:
  email: always
env:
  global:
    secure: g2dstqLa9NQF85UgXx3nE1NfadX/PUKYQ3ON3tg81hd8zYh83Dqs3Rwk7ZK/SBvvK5eRRJvI0dQfayUQTktgSKng8ZPdLxG8PTgIiXynyIafkkJwmPdtAqRErsLj1hyyok0H0TAbeEmaIzhwM2bZpmzmZbYR0KfWJYl3UCriZZV2fm21VQeUK1+0QWlxk3w+QvaGfxqQDuRfalNWA3KyMJ0ondJPMFe+wJvLnjl0yD3rOC+q2IIl1brKiIbVH5auFKDYZJRZP9Tzq7mb2i8S8EugbV+imx2I8Ca38AtwIH2Oa9i40fVm/auqi0Bxqk33llhQ1JgJYXUddaTJ020IXZv5kKFlHNAULBucDV7TjNnqdYfLmGPGO47d1RtTSsx9KNnaiHeTNkBJhDTNumL5XcJneT+/o+C/EroyLQBqUfapNBQvQlA9k9f3gY/nOQQu8iXnYNZwCF/Tfl08z/9gLZoTqT1n8ixp0l5cSw5LjibwhjiumvwGWxNS8SV+xyR6BaWF1FHdVt0GkoaSp+Qee9WW4KnDfPwy8PNwEHGStLfZdEcuNkvB3lTz625pF6dWGI/+CRSkbf6fgD+PTcLF3LtLBNdCwoDgrXYxLbS54huO/ZWgBfhhBJvNMEBE9gQ+ws0lIqzuuDo+38ZRajnx+I2evNAD9r8vaKuCuTpWTCE=
